version: '3'

services:

  hdfs:
    build:
      context: hdfs
      dockerfile: Dockerfile
    container_name: hdfs
    hostname: hdfs
    tty: true
    ports:
      - "9870:9870"
    volumes:
    - hdfs-data:/hadoop/data

  sds:
    build:
      context: sdc
      dockerfile: Dockerfile
    links:
      - hdfs
      - kafka
    ports:
      - "18630:18630"
    volumes:
    - sdc-data:/data

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

volumes:
  sdc-data:
  hdfs-data:
