version: '3'

services:

  hdfs:
    build:
      context: hdfs
      dockerfile: Dockerfile
    container_name: hdfs
    hostname: hdfs
    ports:
      - 8020:8020
      - 8042:8042
      - 8088:8088
      - 9000:9000
      - 9864:9864
      - 9870:9870
      - 9868:9868
      - 10020:10020
      - 19888:19888
      - 50010:50010
      - 50020:50020
      - 50070:50070
      - 50075:50075
      - 50090:50090
    tty: true

  sds:
    build:
      context: sdc
      dockerfile: Dockerfile
    links:
      - hdfs
    ports:
      - "18630:18630"
    volumes:
    - sdc-data:/data

volumes:
  sdc-data:
